default:
  time:
    time_zone: 8
  scrapy:
    project: 'dg_spider'
    url: "http://localhost:6800"
  flask:
    temp_dir: 'application/temp'
    egg_path: 'dist/dg_spider-1.0-py3.10.egg'


dev:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "123456"
    db: "dg_dev_crawler"
#prod:
#  mysql:
#    host: "localhost"
#    port: 3306
#    username: "root"
#    password: "123456"
#    db: "dg_dev_crawler"


#dev:
#  mysql:
#    host: "172.16.234.200"
#    port: 3306
#    username: "dg_dev"
#    password: "dg_dev"
#    db: "dg_dev_crawler"
